load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load(
    "@prelude//toolchains:python.bzl",
    "system_python_bootstrap_toolchain",
)
load(
    "@prelude//toolchains/go:go_bootstrap_toolchain.bzl",
    "go_bootstrap_distr",
    "go_bootstrap_toolchain",
)
load("@prelude//toolchains/go:go_toolchain.bzl", "go_distr", "go_toolchain")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_rust_toolchain(
    name = "rust",
    default_edition = "2021",
    visibility = ["PUBLIC"],
)

# system_go_toolchain is broken, so we define hermetic go toolchain as a workaround
http_archive(
    name = "archive_go1.25.5.darwin-arm64",
    sha256 = "bed8ebe824e3d3b27e8471d1307f803fc6ab8e1d0eb7a4ae196979bd9b801dd3",
    strip_prefix = "go",
    urls = ["https://go.dev/dl/go1.25.5.darwin-arm64.tar.gz"],
)

http_archive(
    name = "archive_go1.25.5.darwin-amd64",
    sha256 = "b69d51bce599e5381a94ce15263ae644ec84667a5ce23d58dc2e63e2c12a9f56",
    strip_prefix = "go",
    urls = ["https://go.dev/dl/go1.25.5.darwin-amd64.tar.gz"],
)

go_bootstrap_distr(
    name = "go_bootstrap_distr",
    go_os_arch = select({
        "config//os:macos": select({
            "config//cpu:arm64": ("darwin", "arm64"),
            "config//cpu:x86_64": ("darwin", "amd64"),
        }),
    }),
    go_root = select({
        "config//os:macos": select({
            "config//cpu:arm64": ":archive_go1.25.5.darwin-arm64",
            "config//cpu:x86_64": ":archive_go1.25.5.darwin-amd64",
        }),
    }),
)

go_bootstrap_toolchain(
    name = "go_bootstrap",
    env_go_arch = select({
        "config//cpu:arm64": "arm64",
        "config//cpu:x86_64": "amd64",
    }),
    env_go_os = select({
        "config//os:macos": "darwin",
    }),
    go_bootstrap_distr = ":go_bootstrap_distr",
    visibility = ["PUBLIC"],
)

go_distr(
    name = "go_distr",
    go_os_arch = select({
        "config//os:macos": select({
            "config//cpu:arm64": ("darwin", "arm64"),
            "config//cpu:x86_64": ("darwin", "amd64"),
        }),
    }),
    go_root = select({
        "config//os:macos": select({
            "config//cpu:arm64": ":archive_go1.25.5.darwin-arm64",
            "config//cpu:x86_64": ":archive_go1.25.5.darwin-amd64",
        }),
    }),
)

go_toolchain(
    name = "go",
    env_go_arch = select({
        "config//cpu:arm64": "arm64",
        "config//cpu:x86_64": "amd64",
    }),
    env_go_os = select({
        "config//os:linux": "linux",
        "config//os:macos": "darwin",
        "config//os:windows": "windows",
    }),
    go_distr = ":go_distr",
    visibility = ["PUBLIC"],
)